### PR TITLE
Add Italian language

### PR DESCRIPTION
**Pull request by fflorent**
In #404, a user requested to be added to GitLocalize to start translating in italian. 

This PR setup the folder `help/it` for that and adds the Italian option in translation template.

### CODE REVIEW

**Review by paulfitz — APPROVED** [review]
Thanks @fflorent (and @ricpol !)

**Comment by ricpol** [comment]
Thanks guys! However, from the GiltLocalize side of it, it still looks like there is only the French translation available, like this: 

gitloc

Is there anything I should do first?

**Comment by fflorent** [comment]
@ricpol Indeed. This should be better now. Could you confirm?

**Comment by ricpol** [comment]
much better now, thanks! I'll get to work soon, promise!

**Pull request merged**
