### PR TITLE
adding november newsletter

### PR DESCRIPTION
**Pull request by nbush**

### CODE REVIEW

**Comment by paulfitz** [comment]
@dsagal would it be worth sneaking in a quick note about forward authentication changes? 

Something like "For those using forward authentication with Grist, you may need to review your settings - please read https://github.com/gristlabs/grist-core/issues/750#issuecomment-1811082115"

It has been hitting a series of users.

(this is very late to bring this up, so please don't hold newsletter on account of this).

**Comment by dsagal** [comment]
> @dsagal would it be worth sneaking in a quick note about forward authentication changes?
> 
> Something like "For those using forward authentication with Grist, you may need to review your settings - please read [gristlabs/grist-core#750 (comment)](https://github.com/gristlabs/grist-core/issues/750#issuecomment-1811082115)"
> 
> It has been hitting a series of users.
> 
> (this is very late to bring this up, so please don't hold newsletter on account of this).

I agree, this is important. Maybe alert "Self-hosters" in the heading of this item, and the explanation and instructions are here: https://community.getgrist.com/t/a-template-for-self-hosting-grist-with-traefik-and-docker-compose/856/24?u=dmitry-grist. The fix is basically to update grist-core or grist-omnibus.

**Comment by nbush** [comment]
> > @dsagal would it be worth sneaking in a quick note about forward authentication changes?
> > Something like "For those using forward authentication with Grist, you may need to review your settings - please read [gristlabs/grist-core#750 (comment)](https://github.com/gristlabs/grist-core/issues/750#issuecomment-1811082115)"
> > It has been hitting a series of users.
> > (this is very late to bring this up, so please don't hold newsletter on account of this).
> 
> I agree, this is important. Maybe alert "Self-hosters" in the heading of this item, and the explanation and instructions are here: https://community.getgrist.com/t/a-template-for-self-hosting-grist-with-traefik-and-docker-compose/856/24?u=dmitry-grist. The fix is basically to update grist-core or grist-omnibus.

This is mentioned in the current page, but I've added some of @paulfitz 's context:

> ### Security update for self-hosters
> 
> We released a security fix earlier this month related to the suggested configuration of `grist-core` with traefik. For those using forward authentication with Grist, you may need to review your settings. See [Dmitry’s Community post](https://community.getgrist.com/t/a-template-for-self-hosting-grist-with-traefik-and-docker-compose/856/24) for more details.

Let me know if that tracks.

**Comment by paulfitz** [comment]
Maybe @dsagal you could edit your community post to cover the information in https://github.com/gristlabs/grist-core/issues/750#issuecomment-1811082115, so that the newsletter snippet doesn't have to cover both? Users who have Grist completely wrapped by something forwarding a header will have a tough time figuring out what to do otherwise. With that change, @nbush's text works for me.

**Comment by dsagal** [comment]
How about this edit to Nick's version, that includes both links. The two issues affect different users, so this seems easier than editing the responses there.

> ### Security update for self-hosters
> We released a security fix earlier this month related to the suggested configuration of `grist-core` with traefik, as well as for [grist-omnibus](https://github.com/gristlabs/grist-omnibus). For those using forward authentication with Grist, you may need to review your settings. See this [Community update](https://community.getgrist.com/t/a-template-for-self-hosting-grist-with-traefik-and-docker-compose/856/24) for more details.
>
> The fix also affects those who do Grist authentication by forwarding a header for all endpoints (e.g. behind HTTP Basic Auth), as it makes a previously optional flag required. See [this issue](https://github.com/gristlabs/grist-core/issues/750#issuecomment-1811082115) for details.

**Comment by nbush** [comment]
Small edit, but otherwise this looks good. Thanks everyone!

> ### Security update for self-hosters
> 
> We released a security fix earlier this month related to the suggested configuration of `grist-core` with traefik, as well as for [`grist-omnibus`](https://github.com/gristlabs/grist-omnibus). See this [Community update](https://community.getgrist.com/t/a-template-for-self-hosting-grist-with-traefik-and-docker-compose/856/24) for more details.
> 
> The fix also affects those who do Grist authentication by forwarding a header for all endpoints (e.g. behind HTTP Basic Auth), as it makes a previously optional flag required. You may need to review your settings – see [this issue](https://github.com/gristlabs/grist-core/issues/750#issuecomment-1811082115) for details.

**Review by anaisconce — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
