### PR TITLE
table-wide-image-change

### PR DESCRIPTION
**Pull request by MichaelNickolas**
made changes to the images and table-wide rule wording

### CODE REVIEW

**Comment by MichaelNickolas** [comment]
I will make full article formatting changes in a new PR once we approve the image changes.

**Review by nataliemisasi — APPROVED** [review]
looks great

**Review by nbush — CHANGES_REQUESTED** [review]
I think we should establish a practice of deleting unused images so that the dir doesn't get too cluttered. Otherwise looks good!

**Comment by MichaelNickolas** [comment]
> I think we should establish a practice of deleting unused images so that the dir doesn't get too cluttered. Otherwise looks good!

There are no images in the images folder that are not being used.

**Pull request merged**
