### PR TITLE
Fix header on mobile

### PR DESCRIPTION
**Pull request by dsagal**
It also changes header to use position "fixed" and makes the articles scroll in a saner way as part of the page body.

Fixes videos to be limited to screen size.

Fixes two dubious (though working) image URLs.

### CODE REVIEW

**Review by berhalak — APPROVED** [review]
Looks good. Thank you.

One suggestion to maybe add `wm-small-hide` to Logo and title element in topbar.html. On mobile the `Home button` and `Back to Grist` overlap on each other.

**Comment by dsagal** [comment]
How do you feel about adding it to the "Back to Grist" link instead?

**Comment by dsagal** [comment]
@anaisconce , how do you feel about the new header and the disappearance of "Back to Grist" link on small screens? (Preview at https://deploy-preview-188--grist-help-preview.netlify.app/)

**Comment by berhalak** [comment]
Yes, hiding "Back to Grist" is a better option.

**Comment by anaisconce** [comment]
Hiding "Back to Grist" on mobile looks okay.  On small phones, the header and "Community" link overlap. Might need to hide "

image

**Comment by dsagal** [comment]
> Hiding "Back to Grist" on mobile looks okay. On small phones, the header and "Community" link overlap. Might need to hide "
> 
> image

I see. There was CSS to hide text to avoid overlap on Firefox, I just added a tweak to get the effect on Chrome.

**Pull request merged**
